"""empty message

Revision ID: 661b8679f37a
Revises: f81de45a691b
Create Date: 2023-10-28 10:00:08.020920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661b8679f37a'
down_revision = 'f81de45a691b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('grave_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('grave_number',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
