"""empty message

Revision ID: a912f8436526
Revises: 0d5888537003
Create Date: 2023-10-30 15:36:40.126905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a912f8436526'
down_revision = '0d5888537003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_column('trash_data_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trash_data_old', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
