"""empty message

Revision ID: 049684381d5c
Revises: 36deb80b9cff
Create Date: 2023-07-09 15:23:31.024654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049684381d5c'
down_revision = '36deb80b9cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.drop_constraint('archaeological_sites_researcher_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'researchers', ['researcher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('archaeological_sites_researcher_id_fkey', 'researchers', ['researcher_id'], ['id'])

    # ### end Alembic commands ###
