"""empty message

Revision ID: 1fac38ce87ed
Revises: 402a24421be6
Create Date: 2024-05-05 11:44:43.275043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fac38ce87ed'
down_revision = '402a24421be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federal_districts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federal_districts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='federal_districts_pkey')
    )
    # ### end Alembic commands ###
