"""empty message

Revision ID: 324dc84fb2f9
Revises: 0ff122203aea
Create Date: 2023-11-30 22:37:40.096950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324dc84fb2f9'
down_revision = '0ff122203aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
