"""empty message

Revision ID: 411eda325ce3
Revises: 324dc84fb2f9
Create Date: 2023-11-30 22:40:24.150572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411eda325ce3'
down_revision = '324dc84fb2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
