"""empty message

Revision ID: 41fcdc202626
Revises: 55d3d4e8a6c9
Create Date: 2023-06-23 13:21:16.678840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fcdc202626'
down_revision = '55d3d4e8a6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database_users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database_users', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
