"""empty message

Revision ID: 4761a404b74c
Revises: 70dd70c03f32
Create Date: 2023-08-03 12:14:35.861014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4761a404b74c'
down_revision = '70dd70c03f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('grave_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('grave_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
