"""empty message

Revision ID: 655fa3138624
Revises: 5ed6eb2f4b39
Create Date: 2023-07-21 13:47:50.659718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655fa3138624'
down_revision = '5ed6eb2f4b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grave_type', sa.String(length=32), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_column('grave_type')

    # ### end Alembic commands ###
