"""empty message

Revision ID: 81a1b74cec67
Revises: 1fac38ce87ed
Create Date: 2024-05-05 15:44:34.094154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a1b74cec67'
down_revision = '1fac38ce87ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplementary_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('object_storage_key', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplementary_files', schema=None) as batch_op:
        batch_op.drop_column('object_storage_key')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
