"""empty message

Revision ID: bf4bbe8255f0
Revises: eae18cf58e46
Create Date: 2023-08-15 22:00:17.701760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4bbe8255f0'
down_revision = 'eae18cf58e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_from_fastapi')
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('edited_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('invidiv_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('individ_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('individ_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.alter_column('sex_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('epoch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('edited_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('preservation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('preservation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('federal_districts_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sites_epochs', schema=None) as batch_op:
        batch_op.alter_column('archaeological_site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('epoch_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sites_researchers', schema=None) as batch_op:
        batch_op.alter_column('archaeological_site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('researcher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites_researchers', schema=None) as batch_op:
        batch_op.alter_column('researcher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('archaeological_site_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sites_epochs', schema=None) as batch_op:
        batch_op.alter_column('epoch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('archaeological_site_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.alter_column('federal_districts_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('preservation', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('individs', schema=None) as batch_op:
        batch_op.alter_column('preservation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('edited_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('epoch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sex_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('individ_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('individ_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('invidiv_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.alter_column('region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('edited_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('alembic_version_from_fastapi',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_from_fastapi_pkc')
    )
    # ### end Alembic commands ###
