"""empty message

Revision ID: d8dfcfd6ebb6
Revises: 8e76eff80671
Create Date: 2023-07-05 13:08:57.219468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dfcfd6ebb6'
down_revision = '8e76eff80671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_column('plast')
        batch_op.drop_column('horizont')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horizont', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plast', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
