"""empty message

Revision ID: dd3d98fb8529
Revises: e01e51cf2840
Create Date: 2023-08-02 22:41:35.064078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3d98fb8529'
down_revision = 'e01e51cf2840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited_by', sa.Integer(), nullable=True))
        batch_op.drop_constraint('archaeological_sites_creator_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('archaeological_sites_editor_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'database_users', ['edited_by'], ['id'])
        batch_op.create_foreign_key(None, 'database_users', ['created_by'], ['id'])
        batch_op.drop_column('creator_id')
        batch_op.drop_column('editor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('archaeological_sites_editor_id_fkey', 'database_users', ['editor_id'], ['id'])
        batch_op.create_foreign_key('archaeological_sites_creator_id_fkey', 'database_users', ['creator_id'], ['id'])
        batch_op.drop_column('edited_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
