"""empty message

Revision ID: e01e51cf2840
Revises: 4b5b97fac645
Create Date: 2023-08-02 22:32:08.578128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01e51cf2840'
down_revision = '4b5b97fac645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.drop_constraint('archaeological_sites_researcher_id_fkey', type_='foreignkey')
        batch_op.drop_column('researcher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('researcher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('archaeological_sites_researcher_id_fkey', 'researchers', ['researcher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
