"""empty message

Revision ID: e1a7f5721414
Revises: d8dfcfd6ebb6
Create Date: 2023-07-05 14:15:09.700417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a7f5721414'
down_revision = 'd8dfcfd6ebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kurgan_number', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graves', schema=None) as batch_op:
        batch_op.drop_column('kurgan_number')

    # ### end Alembic commands ###
