"""empty message

Revision ID: eae18cf58e46
Revises: f83de2a39cb7
Create Date: 2023-08-15 16:30:44.065204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae18cf58e46'
down_revision = 'f83de2a39cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_from_fastapi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version_from_fastapi',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_from_fastapi_pkc')
    )
    # ### end Alembic commands ###
