"""empty message

Revision ID: f81de45a691b
Revises: 
Create Date: 2023-09-25 09:55:27.228275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81de45a691b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epochs_name'), ['name'], unique=False)

    op.create_table('federal_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('affiliation', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sex',
    sa.Column('sex', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('sex')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('affiliation', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('federal_districts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['federal_districts_id'], ['federal_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('archaeological_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('long', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archaeological_sites_name'), ['name'], unique=False)

    op.create_table('individs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('sex_type', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('epoch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('preservation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], ),
    sa.ForeignKeyConstraint(['preservation_id'], ['preservation.id'], ),
    sa.ForeignKeyConstraint(['sex_type'], ['sex.sex'], ),
    sa.ForeignKeyConstraint(['site_id'], ['archaeological_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites_epochs',
    sa.Column('archaeological_site_id', sa.Integer(), nullable=True),
    sa.Column('epoch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archaeological_site_id'], ['archaeological_sites.id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], )
    )
    op.create_table('sites_researchers',
    sa.Column('archaeological_site_id', sa.Integer(), nullable=True),
    sa.Column('researcher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archaeological_site_id'], ['archaeological_sites.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], )
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('invidiv_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invidiv_id'], ['individs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('extension', sa.String(length=36), nullable=False),
    sa.Column('individ_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individ_id'], ['individs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grave_type', sa.String(length=32), nullable=True),
    sa.Column('kurgan_number', sa.String(length=32), nullable=True),
    sa.Column('grave_number', sa.Integer(), nullable=False),
    sa.Column('catacomb', sa.Integer(), nullable=True),
    sa.Column('chamber', sa.Integer(), nullable=True),
    sa.Column('trench', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('object', sa.String(length=32), nullable=True),
    sa.Column('layer', sa.String(length=32), nullable=True),
    sa.Column('square', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('niveau_point', sa.Integer(), nullable=True),
    sa.Column('tachymeter_point', sa.Integer(), nullable=True),
    sa.Column('skeleton', sa.String(length=32), nullable=True),
    sa.Column('individ_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individ_id'], ['individs.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['archaeological_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graves')
    op.drop_table('files')
    op.drop_table('comments')
    op.drop_table('sites_researchers')
    op.drop_table('sites_epochs')
    op.drop_table('individs')
    with op.batch_alter_table('archaeological_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archaeological_sites_name'))

    op.drop_table('archaeological_sites')
    op.drop_table('regions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sex')
    op.drop_table('researchers')
    op.drop_table('preservation')
    op.drop_table('federal_districts')
    with op.batch_alter_table('epochs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epochs_name'))

    op.drop_table('epochs')
    # ### end Alembic commands ###
